Contact form
banzaman/portfolio-02 pull request #3
Opened 2022-01-11 22:57 UTC by banzaman

- Created a contact form

2022-01-11 23:53 UTC, julie-ify requested changes
## Hi team,

Good job so far!

## Highlight!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive commit messages ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-11 23:53 UTC, julie-ify commented on style.css
> +}
- [ ] Nice job so far 🔥. Please consider adding a margin-top to this element so as to give it the proper spacing from other elements.
- [ ] The color for this element is different from the template. The template has `#172B4D` as the color. Why don't you stick to the template designs and colors so that we achieve the same result as the template 😄

2022-01-11 23:53 UTC, julie-ify commented on style.css
> +}
- [ ] Please let's implement the button hover effect here as it is in the template. Please check the template and consider applying the hover effect to your button.
- [ ] Let's add a `cursor: pointer;` property so that we have a pointer cursor when we hover over the button`. This will help improve user experience and interaction on our page.

2022-01-11 23:53 UTC, julie-ify commented on style.css
> +}
- [ ] Nice job so far 🔥. Please consider adding a margin buttom to this element so as to give it the proper spacing

- [ ] The `background-color` for these icons is different from the template. The template has `#505F79` as the `background-color`. Why don't you stick to the template designs so that we achieve the same result as the template ?😄

2022-01-13 16:58 UTC, rotimiazeez requested changes
# Hi TEAM👏, 

### Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 16:58 UTC, rotimiazeez commented on style.css
> +}
- [ ] Kindly make sure the icons follow the same design as seen in the original template✌✌
Your Design | Figma Design
:---:|:---:
![](https://user-images.githubusercontent.com/44624138/149374211-a3773caf-194b-44bd-b35d-35591d4f3dc5.png) | ![](https://user-images.githubusercontent.com/44624138/149374334-007c7cab-7976-41d7-9d70-b385b18cb5bf.png)

2022-01-13 17:38 UTC, moise10r approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Whoistolu** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- [ OPTIONAL] Kindly, Add a screenshot of you project in the README file to make your readme more professional 



Cheers and Happy coding!👏👏👏💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 19:10 UTC, merged